baseURL = "https://churious.github.io/"
title = "Churious"
languageCode = "ko-kr"
theme = ["PaperMod"]

[params]
  defaultTheme = "auto"
  description = "Crafting with Curiosity"
  
  # 블로그 글 설정
  ShowReadingTime = true
  ShowShareButtons = false
  
  # 로고 설정
  label = { text = "Churious", icon = "/images/logo.svg", iconHeight = 35 }

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
